### ISSUE TITLE
Module is checking for the wrong config file name

### ISSUE THREAD

**Issue by Autre31415** [rooseveltframework/express-html-validator#116]
This module's readme, Roosevelt's readme, and html-validate's own docs indicate that the config file is named `.htmlValidate.json`, but for some reason this module is checking for `.htmlvalidator.json` [here](https://github.com/rooseveltframework/express-html-validator/blob/6664b2f857865db3c3fd8742a936ccb310c5fb0f/index.js#L62), this should be updated to match the documentation.

**Comment by wiksien** [comment]
I will do that.
